USE [master]
GO
/****** Object:  Database [CBIAssessment]    Script Date: 2019/01/30 11:29:03 AM ******/
CREATE DATABASE [CBIAssessment]
 GO

ALTER DATABASE [CBIAssessment] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CBIAssessment].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CBIAssessment] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CBIAssessment] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CBIAssessment] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CBIAssessment] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CBIAssessment] SET ARITHABORT OFF 
GO
ALTER DATABASE [CBIAssessment] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [CBIAssessment] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CBIAssessment] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CBIAssessment] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CBIAssessment] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CBIAssessment] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CBIAssessment] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CBIAssessment] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CBIAssessment] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CBIAssessment] SET  ENABLE_BROKER 
GO
ALTER DATABASE [CBIAssessment] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CBIAssessment] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CBIAssessment] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CBIAssessment] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CBIAssessment] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CBIAssessment] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CBIAssessment] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CBIAssessment] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [CBIAssessment] SET  MULTI_USER 
GO
ALTER DATABASE [CBIAssessment] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CBIAssessment] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CBIAssessment] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CBIAssessment] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [CBIAssessment] SET DELAYED_DURABILITY = DISABLED 
GO
USE [CBIAssessment]
GO
/****** Object:  User [PHONEBOOKUSER]    Script Date: 2019/01/30 11:29:04 AM ******/
CREATE USER [PHONEBOOKUSER] FOR LOGIN [PHONEBOOKUSER] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_datareader] ADD MEMBER [PHONEBOOKUSER]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [PHONEBOOKUSER]
GO
/****** Object:  Table [dbo].[Entry]    Script Date: 2019/01/30 11:29:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Entry](
	[EntryId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
	[PhoneNumber] [int] NULL,
	[PhonebookID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[EntryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Phonebook]    Script Date: 2019/01/30 11:29:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Phonebook](
	[PhonebookID] [int] IDENTITY(100,10) NOT NULL,
	[Name] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[PhonebookID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Entry]  WITH CHECK ADD FOREIGN KEY([PhonebookID])
REFERENCES [dbo].[Phonebook] ([PhonebookID])
GO
USE [master]
GO
ALTER DATABASE [CBIAssessment] SET  READ_WRITE 
GO
